#!/bin/sh

set -eu

# Default to the checkout containing this installer. The repository may live
# anywhere on another machine, so do not assume ~/Software/tmux.
default_config_dir=$(CDPATH='' cd "$(dirname "$0")" && pwd -P) || exit 1
install_tmux=1
install_herdr=1

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

path_exists() {
  [ -e "$1" ] || [ -L "$1" ]
}

checkbox() {
  if [ "$1" -eq 1 ]; then
    printf '[x]'
  else
    printf '[ ]'
  fi
}

toggle() {
  if [ "$1" -eq 1 ]; then
    printf '0'
  else
    printf '1'
  fi
}

next_backup_path() {
  original_path=$1
  backup_path=${original_path}.old
  backup_number=1

  while path_exists "$backup_path"; do
    backup_path=${original_path}.old.${backup_number}
    backup_number=$((backup_number + 1))
  done

  printf '%s\n' "$backup_path"
}

prompt_components() {
  while :; do
    printf '\nSelect components (type a number to toggle, then press Enter):\n'
    printf '  %s  1) tmux\n' "$(checkbox "$install_tmux")"
    printf '  %s  2) Herdr\n' "$(checkbox "$install_herdr")"
    printf '      a) Select both    n) Select none    q) Quit\n'
    printf 'Selection [Enter to continue]: '
    IFS= read -r component_choice || exit 1

    case $component_choice in
      '')
        if [ "$install_tmux" -eq 1 ] || [ "$install_herdr" -eq 1 ]; then
          return
        fi
        printf 'Select at least one component.\n'
        ;;
      1)
        install_tmux=$(toggle "$install_tmux")
        ;;
      2)
        install_herdr=$(toggle "$install_herdr")
        ;;
      a | A)
        install_tmux=1
        install_herdr=1
        ;;
      n | N)
        install_tmux=0
        install_herdr=0
        ;;
      q | Q)
        printf 'Installation cancelled.\n'
        exit 0
        ;;
      *)
        printf 'Unknown selection: %s\n' "$component_choice"
        ;;
    esac
  done
}

prompt_config_dir() {
  while :; do
    printf '\nConfiguration directory [%s]: ' "$default_config_dir"
    IFS= read -r entered_config_dir || exit 1
    config_dir=${entered_config_dir:-$default_config_dir}

    case $config_dir in
      \~)
        config_dir=$HOME
        ;;
      \~/*)
        config_dir=$HOME/${config_dir#\~/}
        ;;
      /*)
        ;;
      *)
        config_dir=$PWD/$config_dir
        ;;
    esac

    if [ ! -d "$config_dir" ]; then
      printf 'Directory does not exist: %s\n' "$config_dir" >&2
      continue
    fi

    config_dir=$(CDPATH='' cd "$config_dir" && pwd -P) || continue

    missing_files=
    if [ "$install_tmux" -eq 1 ]; then
      for required_file in \
        tmux.conf \
        white_black_color \
        tmux-resurrect/resurrect.tmux \
        tmux-open/open.tmux
      do
        if [ ! -f "$config_dir/$required_file" ]; then
          missing_files="$missing_files $required_file"
        fi
      done
    fi

    if [ "$install_herdr" -eq 1 ]; then
      for required_file in herdr.toml herdr-tmux-compat/herdr-plugin.toml; do
        if [ ! -f "$config_dir/$required_file" ]; then
          missing_files="$missing_files $required_file"
        fi
      done
    fi

    if [ -n "$missing_files" ]; then
      printf 'The directory is not a complete configuration checkout. Missing:%s\n' \
        "$missing_files" >&2
      continue
    fi

    return
  done
}

tmux_config_contents() {
  escaped_config_dir=$(printf '%s' "$config_dir" | sed 's/[\\$\"]/\\&/g')
  printf '%s\n' '# Generated by the tmux/Herdr configuration installer.'
  printf 'source-file "%s/tmux.conf"\n' "$escaped_config_dir"
  printf 'source-file "%s/white_black_color"\n' "$escaped_config_dir"
}

plan_backups() {
  tmux_config_path=$HOME/.tmux.conf
  herdr_config_path=$HOME/.config/herdr/config.toml
  tmux_backup_path=
  herdr_backup_path=
  write_tmux_config=0
  link_herdr_config=0

  if [ "$install_tmux" -eq 1 ]; then
    desired_tmux_config=$(tmux_config_contents)
    current_tmux_config=
    if [ -f "$tmux_config_path" ] && [ ! -L "$tmux_config_path" ]; then
      current_tmux_config=$(cat "$tmux_config_path")
    fi

    if ! path_exists "$tmux_config_path" || \
      [ "$current_tmux_config" != "$desired_tmux_config" ]; then
      write_tmux_config=1
      if path_exists "$tmux_config_path"; then
        tmux_backup_path=$(next_backup_path "$tmux_config_path")
        printf 'Warning: %s will be moved to %s\n' \
          "$tmux_config_path" "$tmux_backup_path"
      fi
    fi
  fi

  if [ "$install_herdr" -eq 1 ]; then
    desired_herdr_target=$config_dir/herdr.toml
    current_herdr_target=
    if [ -L "$herdr_config_path" ]; then
      current_herdr_target=$(readlink "$herdr_config_path")
    fi

    if [ "$current_herdr_target" != "$desired_herdr_target" ]; then
      link_herdr_config=1
      if path_exists "$herdr_config_path"; then
        herdr_backup_path=$(next_backup_path "$herdr_config_path")
        printf 'Warning: %s will be moved to %s\n' \
          "$herdr_config_path" "$herdr_backup_path"
      fi
    fi
  fi
}

confirm_installation() {
  printf '\nConfiguration directory: %s\n' "$config_dir"
  printf 'Components:'
  [ "$install_tmux" -eq 1 ] && printf ' tmux'
  [ "$install_herdr" -eq 1 ] && printf ' Herdr'
  printf '\nContinue? [y/N]: '
  IFS= read -r confirmation || exit 1

  case $confirmation in
    y | Y | yes | YES | Yes)
      ;;
    *)
      printf 'Installation cancelled.\n'
      exit 0
      ;;
  esac
}

install_packages() {
  set --

  if [ "$install_tmux" -eq 1 ] && ! command -v tmux >/dev/null 2>&1; then
    set -- "$@" tmux
  fi

  if [ "$install_herdr" -eq 1 ]; then
    command -v herdr >/dev/null 2>&1 || set -- "$@" herdr
    command -v jq >/dev/null 2>&1 || set -- "$@" jq
    command -v python3 >/dev/null 2>&1 || set -- "$@" python
  fi

  if [ "$#" -eq 0 ]; then
    printf 'Required programs are already installed.\n'
    return
  fi

  command -v brew >/dev/null 2>&1 || \
    die "Homebrew is required to install:$*. See https://brew.sh/"

  printf 'Installing with Homebrew:%s\n' " $*"
  brew install "$@"
}

install_tmux_config() {
  if [ "$install_tmux" -ne 1 ]; then
    return 0
  fi

  if [ -n "$tmux_backup_path" ]; then
    mv "$tmux_config_path" "$tmux_backup_path"
  fi

  if [ "$write_tmux_config" -eq 1 ]; then
    tmux_config_contents >"$tmux_config_path"
    printf 'Installed tmux configuration: %s\n' "$tmux_config_path"
  else
    printf 'tmux configuration is already current.\n'
  fi

  if tmux list-sessions >/dev/null 2>&1; then
    if tmux source-file "$tmux_config_path"; then
      printf 'Reloaded the running tmux server.\n'
    else
      printf 'Warning: tmux is installed, but the running server could not be reloaded.\n' >&2
    fi
  fi
}

install_herdr_config() {
  if [ "$install_herdr" -ne 1 ]; then
    return 0
  fi

  HERDR_CONFIG_PATH=$config_dir/herdr.toml herdr config check

  mkdir -p "$HOME/.config/herdr"
  if [ -n "$herdr_backup_path" ]; then
    mv "$herdr_config_path" "$herdr_backup_path"
  fi

  if [ "$link_herdr_config" -eq 1 ]; then
    ln -s "$config_dir/herdr.toml" "$herdr_config_path"
    printf 'Linked Herdr configuration: %s\n' "$herdr_config_path"
  else
    printf 'Herdr configuration link is already current.\n'
  fi

  herdr plugin link "$config_dir/herdr-tmux-compat" --enabled >/dev/null
  printf 'Linked and enabled the local Herdr compatibility plugin.\n'
  if herdr server reload-config >/dev/null 2>&1; then
    printf 'Reloaded the running Herdr server.\n'
  else
    printf 'Herdr will load the configuration when it starts.\n'
  fi
}

if [ ! -t 0 ]; then
  die 'this installer must be run interactively'
fi

prompt_components
prompt_config_dir
plan_backups
confirm_installation
install_packages
install_tmux_config
install_herdr_config

printf '\nInstallation complete.\n'
